"""hotel_service

Revision ID: 5c09d4320e14
Revises: 7936e085d3f8
Create Date: 2022-12-07 16:50:33.751765

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5c09d4320e14'
down_revision = '7936e085d3f8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hotel_idempotent_request',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('order_id', sa.Integer(), nullable=True),
    sa.Column('idempotent_key', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_hotel_idempotent_request_id'), 'hotel_idempotent_request', ['id'], unique=False)
    op.create_table('hotel_orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('hotel_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_hotel_orders_id'), 'hotel_orders', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_hotel_orders_id'), table_name='hotel_orders')
    op.drop_table('hotel_orders')
    op.drop_index(op.f('ix_hotel_idempotent_request_id'), table_name='hotel_idempotent_request')
    op.drop_table('hotel_idempotent_request')
    # ### end Alembic commands ###
