"""catalog_service

Revision ID: 97960180282d
Revises: bad992d0eda3
Create Date: 2022-12-12 18:58:02.798610

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '97960180282d'
down_revision = 'bad992d0eda3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('catalog',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hotel_id', sa.Integer(), nullable=True),
    sa.Column('flight_id', sa.Integer(), nullable=True),
    sa.Column('country_id', sa.Integer(), nullable=True),
    sa.Column('date_from', sa.Date(), nullable=True),
    sa.Column('date_to', sa.Date(), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_catalog_id'), 'catalog', ['id'], unique=False)
    op.add_column('orders', sa.Column('hotel_id', sa.Integer(), nullable=True))
    op.add_column('orders', sa.Column('flight_id', sa.Integer(), nullable=True))
    op.add_column('orders', sa.Column('country_id', sa.Integer(), nullable=True))
    op.add_column('orders', sa.Column('date_from', sa.Date(), nullable=True))
    op.add_column('orders', sa.Column('date_to', sa.Date(), nullable=True))
    op.drop_column('orders', 'address')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('address', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_column('orders', 'date_to')
    op.drop_column('orders', 'date_from')
    op.drop_column('orders', 'country_id')
    op.drop_column('orders', 'flight_id')
    op.drop_column('orders', 'hotel_id')
    op.drop_index(op.f('ix_catalog_id'), table_name='catalog')
    op.drop_table('catalog')
    # ### end Alembic commands ###
