"""ticket_service

Revision ID: 9ebd91a453ec
Revises: 5c09d4320e14
Create Date: 2022-12-07 17:14:54.502184

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9ebd91a453ec'
down_revision = '5c09d4320e14'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ticket_idempotent_request',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('order_id', sa.Integer(), nullable=True),
    sa.Column('idempotent_key', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ticket_idempotent_request_id'), 'ticket_idempotent_request', ['id'], unique=False)
    op.create_table('ticket_orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('flight_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ticket_orders_id'), 'ticket_orders', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ticket_orders_id'), table_name='ticket_orders')
    op.drop_table('ticket_orders')
    op.drop_index(op.f('ix_ticket_idempotent_request_id'), table_name='ticket_idempotent_request')
    op.drop_table('ticket_idempotent_request')
    # ### end Alembic commands ###
