"""pyment_service

Revision ID: bad992d0eda3
Revises: f3997c2fba30
Create Date: 2022-12-10 12:16:32.956176

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bad992d0eda3'
down_revision = 'f3997c2fba30'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pyment_account_user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('debit', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pyment_account_user_id'), 'pyment_account_user', ['id'], unique=False)
    op.create_table('pyment_orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('order_id', sa.Integer(), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('success', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pyment_orders_id'), 'pyment_orders', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pyment_orders_id'), table_name='pyment_orders')
    op.drop_table('pyment_orders')
    op.drop_index(op.f('ix_pyment_account_user_id'), table_name='pyment_account_user')
    op.drop_table('pyment_account_user')
    # ### end Alembic commands ###
