"""modify_order_service

Revision ID: f3997c2fba30
Revises: 45b76b6e1784
Create Date: 2022-12-10 11:48:07.264016

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f3997c2fba30'
down_revision = '45b76b6e1784'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('price', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'price')
    # ### end Alembic commands ###
