apiVersion: v1
kind: Service
metadata:
  name: order-service
  namespace: {{ .Values.namespace }}
  labels:
      {{- include "hw_9_chart.orderSelectorLabels" . | nindent 6 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: web
      port: {{ .Values.service.port }}
      targetPort: 8000
  selector:
    {{- include "hw_9_chart.orderSelectorLabels" . | nindent 4 }}
