apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "hw_9_chart.fullname" . }}
  namespace: {{ .Values.namespace }}
spec:
  endpoints:
    - port: web
      interval: 15s
      path: /metrics
  selector:
    matchLabels:
      {{- include "hw_9_chart.selectorLabels" . | nindent 6 }}
