{
 "title": "OTUS Copy",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "Ingress nginx controller", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "HTTP: RPS",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 9, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "sum(rate(nginx_ingress_controller_requests{}[1m]))",
     "legendFormat": "Request rate"
    },
    {
     "expr": "sum(rate(nginx_ingress_controller_requests{status=\"500\"}[1m]))",
     "legendFormat": "Error rate"
    }
   ]
  },
  {
   "title": "HTTP: Latency",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 9, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(1, sum by (le) (rate(nginx_ingress_controller_request_duration_seconds_bucket[1m])))",
     "legendFormat": "inf"
    },
    {
     "expr": "histogram_quantile(0.99, sum by (le) (rate(nginx_ingress_controller_request_duration_seconds_bucket[1m])))",
     "legendFormat": "q99"
    },
    {
     "expr": "histogram_quantile(0.95, sum by (le) (rate(nginx_ingress_controller_request_duration_seconds_bucket[1m])))",
     "legendFormat": "q95"
    },
    {
     "expr": "histogram_quantile(0.5, sum by (le) (rate(nginx_ingress_controller_request_duration_seconds_bucket[1m])))",
     "legendFormat": "q50"
    }
   ]
  },
  { "title": "Kubernetes", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "Pods CPU",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 9, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "cpu" } },
   "targets": [
    {
     "expr": "rate(container_cpu_usage_seconds_total{namespace=\"otus-hw-volodina\"}[3m])",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Pods memory",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 9, "x": 9, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "rate(container_memory_working_set_bytes{namespace=\"otus-hw-volodina\"}[3m])",
     "legendFormat": "{{pod}}"
    }
   ]
  }
 ]
}