apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: users
  namespace: {{ .Values.namespace }}
  annotations:
    nginx.ingress.kubernetes.io/auth-url: http://poleteli.com/auth
    nginx.ingress.kubernetes.io/auth-response-headers: x-user_id
    kubernetes.io/ingress.class: nginx
spec:
  rules:
    - host: poleteli.com
      http:
        paths:
          - path: /user
            pathType: Prefix
            backend:
              service:
                name: {{ include "hw_chart.fullname" . }}
                port:
                  number: 8000
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: auth
  namespace: {{ .Values.namespace }}
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
    - host: poleteli.com
      http:
        paths:
          - path: /login
            pathType: Prefix
            backend:
              service:
                name: {{ include "hw_chart.fullname" . }}
                port:
                  number: 8000

          - path: /logout
            pathType: Prefix
            backend:
              service:
                name: {{ include "hw_chart.fullname" . }}
                port:
                  number: 8000

          - path: /registration
            pathType: Prefix
            backend:
              service:
                name: {{ include "hw_chart.fullname" . }}
                port:
                  number: 8000

          - path: /auth
            pathType: Prefix
            backend:
              service:
                name: {{ include "hw_chart.fullname" . }}
                port:
                  number: 8000
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: orders
  namespace: {{ .Values.namespace }}
  annotations:
    nginx.ingress.kubernetes.io/auth-url: http://poleteli.com/auth
    nginx.ingress.kubernetes.io/auth-response-headers: x-user_id
    kubernetes.io/ingress.class: nginx
spec:
  rules:
    - host: poleteli.com
      http:
        paths:
          - path: /create_order
            pathType: Prefix
            backend:
              service:
                name: order-service
                port:
                  number: 8000
          - path: /order
            pathType: Prefix
            backend:
              service:
                name: order-service
                port:
                  number: 8000
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: hotel
  namespace: {{ .Values.namespace }}
  annotations:
    nginx.ingress.kubernetes.io/auth-url: http://poleteli.com/auth
    nginx.ingress.kubernetes.io/auth-response-headers: x-user_id
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  rules:
    - host: poleteli.com
      http:
        paths:
          - path: /hotel/(.*)
            pathType: Prefix
            backend:
              service:
                name: hotel-service
                port:
                  number: 8000
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ticket
  namespace: {{ .Values.namespace }}
  annotations:
    nginx.ingress.kubernetes.io/auth-url: http://poleteli.com/auth
    nginx.ingress.kubernetes.io/auth-response-headers: x-user_id
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  rules:
    - host: poleteli.com
      http:
        paths:
          - path: /ticket/(.*)
            pathType: Prefix
            backend:
              service:
                name: ticket-service
                port:
                  number: 8000
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: pyment
  namespace: {{ .Values.namespace }}
  annotations:
    nginx.ingress.kubernetes.io/auth-url: http://poleteli.com/auth
    nginx.ingress.kubernetes.io/auth-response-headers: x-user_id
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  rules:
    - host: poleteli.com
      http:
        paths:
          - path: /payment/(.*)
            pathType: Prefix
            backend:
              service:
                name: pyment-service
                port:
                  number: 8000

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: notify
  namespace: {{ .Values.namespace }}
  annotations:
    nginx.ingress.kubernetes.io/auth-url: http://poleteli.com/auth
    nginx.ingress.kubernetes.io/auth-response-headers: x-user_id
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  rules:
    - host: poleteli.com
      http:
        paths:
          - path: /notify/(.*)
            pathType: Prefix
            backend:
              service:
                name: notify-service
                port:
                  number: 8000
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: catalog
  namespace: {{ .Values.namespace }}
  annotations:
    nginx.ingress.kubernetes.io/auth-url: http://poleteli.com/auth
    nginx.ingress.kubernetes.io/auth-response-headers: x-user_id
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  rules:
    - host: poleteli.com
      http:
        paths:
          - path: /catalog/(.*)
            pathType: Prefix
            backend:
              service:
                name: catalog-service
                port:
                  number: 8000